"use client";

import { useEffect, useRef, useState } from "react";
import DesktopDemo from "./desktop-demo";
import { ArrowRight, ArrowUp, ArrowUpRight, Check, Code2, Copy, Github, History, Layers3, Menu, MousePointer2, KeyRound, Plus, ShieldCheck, Sparkles, Terminal, Undo2, X } from "lucide-react";

const REPO = "https://github.com/BenchGrid-dev/slate";
const INSTALL = "git clone https://github.com/BenchGrid-dev/slate.git\ncd slate\ncargo build --workspace\n./target/debug/slash";
function Diamond({ className = "" }: { className?: string }) { return <span aria-hidden="true" className={`diamond ${className}`}>◆</span>; }
function Brand({ footer = false }: { footer?: boolean }) {
  return <div className={`brand ${footer ? "brand-footer" : ""}`}><a href="#" className="slate-wordmark" aria-label="Slate home"><img className="slate-logo-mark" src="/slate-logo-mark.svg" width={36} height={36} alt="" aria-hidden="true" /><span className="brand-type">Slate</span></a><span className="brand-by">by</span><a className="benchgrid-wordmark" href="https://benchgrid.dev" aria-label="BenchGrid website">benchgrid<span>.</span></a></div>;
}
function Dots() { return <span className="window-dots" aria-hidden="true"><i /><i /><i /></span>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const [backend, setBackend] = useState<"claude" | "codex">("claude");
  const copyTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (copyTimer.current) clearTimeout(copyTimer.current); }, []);
  useEffect(() => { function escape(e: KeyboardEvent) { if (e.key === "Escape") setMenuOpen(false); } window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, []);
  async function copyInstall() {
    try { await navigator.clipboard.writeText(INSTALL); setCopied(true); setCopyError(false); copyTimer.current = setTimeout(() => setCopied(false), 2400); }
    catch { setCopyError(true); }
  }

  return <>
    <div className="hero-landscape" aria-hidden="true" />
    <header className="site-header"><Brand /><nav id="mobile-nav" aria-label="Main navigation" className={menuOpen ? "nav-open" : ""}>{[["Why Slate", "#why-slate"], ["The experience", "#experience"], ["Open source", "#open-source"]].map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}<a href={`${REPO}#documentation`} target="_blank" rel="noreferrer">Docs <ArrowUpRight size={12} /></a></nav><a className="button button-dark nav-cta" href="#get-started">Meet your new desktop <ArrowUpRight size={13} /></a><button className="mobile-menu" aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} aria-controls="mobile-nav" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></header>
    <main id="main">
      <section className="hero" aria-labelledby="hero-title">
        <a className="announcement" href={`${REPO}/blob/main/CHANGELOG.md`} target="_blank" rel="noreferrer"><span className="online-dot" /> A fresh start for the desktop <span className="announcement-version">Pre-alpha</span><ArrowRight size={12} /></a>
        <h1 id="hero-title">A little less <em>human.</em><br />A lot more possible.</h1>
        <p className="hero-description">An operating system that works <span>with you.</span><br />Your apps, your agent, and your ideas — finally in the same place.</p>
        <div className="hero-actions"><a className="button button-dark" href="#get-started">Get started with Slate <ArrowRight size={15} /></a><a className="button button-glass" href={REPO} target="_blank" rel="noreferrer"><Github size={16} /> GitHub repo</a></div>
        <div className="hero-promises"><span><Code2 /> Open source</span><span><Layers3 /> Built on NixOS</span><span><MousePointer2 /> Always your desktop</span></div>
        <div id="experience" className="demo-section"><DesktopDemo /></div>
      </section>

      <section className="foundation page-width" aria-label="Built on open foundations"><p>A fresh perspective. A familiar foundation.</p><div className="foundation-logos"><span className="foundation-brand foundation-nixos"><img src="/brands/nixos.svg" width={170} height={92} alt="NixOS" /></span>{[
          { name: "Linux", src: "/brands/linux.png", width: 32, height: 39 },
          { name: "Rust", src: "/brands/rust.png", width: 32, height: 32 },
          { name: "Wayland", src: "/brands/wayland.png", width: 32, height: 32 },
          { name: "Claude Code", src: "/brands/claude.png", width: 32, height: 32 },
          { name: "Codex", src: "/brands/codex.svg", width: 32, height: 32 },
        ].map(brand => <span key={brand.name} className="foundation-brand"><img src={brand.src} width={brand.width} height={brand.height} alt="" aria-hidden="true" /><span>{brand.name}</span></span>)}</div></section>

      <section id="why-slate" className="capabilities page-width"><div className="section-heading"><div><h2>One desktop.<br className="mobile-break" /> <em>New possibilities.</em></h2></div><p>Less switching. More doing.<br />Everything your agent needs to help, woven into the place you already work.</p></div>
        <div className="feature-grid">
          <article className="feature feature-agent"><div className="feature-top"><span className="feature-label"><Sparkles size={12} /> A PLACE FOR YOUR AGENT</span><span className="feature-icon"><Diamond /></span></div><h3>You do your thing.<br />Slate handles the next.</h3><p>Give your agent a task across apps, files, and your system. Keep your focus while it finds its flow.</p><div className="mini-conversation"><div><Diamond /><span>Open the report and arrange my windows.</span><ArrowUp size={14} /></div><div><Check size={12} /> Report opened in Firefox <span>done</span></div><div><Check size={12} /> Windows arranged side by side <span>done</span></div><div className="conversation-status"><span className="online-dot" /> All set. Make yourself at home.</div></div></article>
          <article className="feature feature-seat"><div className="feature-top"><span className="feature-label"><MousePointer2 size={12} /> ROOM FOR TWO</span><MousePointer2 size={17} /></div><h3>Shared space.<br />Independent focus.</h3><p>A dedicated Wayland input seat gives your agent its own keyboard, pointer, and place to work.</p><div className="seat-illustration" aria-hidden="true"><div className="seat-window seat-human"><Dots /><div className="skeleton-line" /><div className="skeleton-line short" /><div className="skeleton-line" /><MousePointer2 className="seat-cursor" fill="currentColor" /><span>You</span></div><div className="seat-window seat-agent"><Diamond /><div className="skeleton-line" /><div className="skeleton-line short" /><div className="skeleton-line" /><MousePointer2 className="seat-cursor" fill="currentColor" /><span>Slate</span></div><div className="seat-baseline" /></div></article>
          <article className="feature feature-small"><Terminal className="small-feature-icon" size={20} /><h3>Say it. Or shell it.</h3><p>Natural language and familiar commands, together in one conversational shell.</p><div className="code-snippet"><span>~/workspace</span><code><b>›</b> !git status</code><code><b>◆</b> What changed today?<i /></code></div></article>
          <article className="feature feature-small"><ShieldCheck className="small-feature-icon" size={20} /><h3>A little help. Your say.</h3><p>Task records and configurable approvals keep you close to what happens next.</p><div className="approval-example"><span><ShieldCheck size={13} /> A moment for your approval</span><div><span>Review action</span><span>Allow <Check size={10} /></span></div></div></article>
          <article className="feature feature-small feature-undo"><History className="small-feature-icon" size={20} /><h3>Room to change your mind.</h3><p>Preview and restore scoped local file changes with btrfs task snapshots.</p><div className="undo-example"><span><i />Before your task</span><div /><span><i />A fresh start</span><Undo2 size={18} /></div></article>
        </div>
      </section>

      <section className="agent-choice page-width"><div className="choice-copy"><h2>Pick your agent.<br /><em>Keep your world.</em></h2><p>Bring Claude Code or Codex, with the account you already use. Slate connects your chosen agent to your desktop, so good ideas can become real work.</p><a className="text-link" href={`${REPO}/blob/main/crates/slash/README.md`} target="_blank" rel="noreferrer">A familiar agent. A whole new workspace. <ArrowUpRight size={14} /></a></div><div className="agent-settings"><div className="settings-title"><span><Diamond /> Your Slate</span><span>AI preferences</span></div><span className="settings-label">CHOOSE YOUR AGENT</span><div className="backend-options">{(["claude", "codex"] as const).map(b => <button key={b} aria-pressed={backend === b} onClick={() => setBackend(b)} className={backend === b ? "selected" : ""}><span className={b === "claude" ? "claude-symbol" : "codex-symbol"}>{b === "claude" ? "✳" : <Code2 size={26} />}</span><span><strong>{b === "claude" ? "Claude Code" : "Codex"}</strong><small>{b === "claude" ? "By Anthropic" : "By OpenAI"}</small></span><span className="radio-circle">{backend === b && <span />}</span></button>)}<button className="byok-option" disabled aria-label="BYOK — Bring your own key, coming soon"><span className="codex-symbol"><KeyRound size={26} /></span><span><strong>BYOK</strong><small>Bring your own key</small></span><span className="coming-soon">Coming soon</span></button></div><div className="settings-detail"><Terminal size={14} /><code>/agent {backend}</code><span>That’s all it takes.</span></div><div className="settings-bottom"><ShieldCheck size={14} /> Your account. Your choice. Connected through the official CLI.</div></div></section>

      <section id="open-source" className="open-source"><div className="page-width"><div className="open-heading"><div><h2>A new kind of desktop.<br />Built <em>in the open.</em></h2></div><p>Great tools should belong to the people who use them. Slate is an open invitation to rethink how we work with our computers.</p></div><div className="principles"><article><Code2 /><h3>Yours to explore.</h3><p>Open source under GPL-3.0. Read the code, follow the thinking, or make it your own.</p><a href={REPO} target="_blank" rel="noreferrer">Explore the source <ArrowUpRight size={13} /></a></article><article><Layers3 /><h3>A solid foundation.</h3><p>A Rust runtime, a NixOS foundation, and a Wayland desktop. Familiar tools, thoughtfully connected.</p><a href={`${REPO}/blob/main/docs/architecture.md`} target="_blank" rel="noreferrer">Under the surface <ArrowUpRight size={13} /></a></article><article><Plus /><h3>Just the beginning.</h3><p>We’re in pre-alpha. Help shape compatibility, the desktop experience, and what comes next.</p><div className="contribute-links"><a href={`${REPO}/blob/main/CONTRIBUTING.md`} target="_blank" rel="noreferrer">Build with us <ArrowUpRight size={13} /></a><a href={`${REPO}/blob/main/docs/roadmap.md`} target="_blank" rel="noreferrer">Roadmap <ArrowUpRight size={13} /></a></div></article></div></div></section>

      <section id="get-started" className="get-started page-width"><div><h2>Your next chapter.<br /><em>Starts here.</em></h2><p>Try the conversational shell today, or bring the full desktop to a NixOS machine.</p><div className="start-actions"><a className="button button-dark" href={`${REPO}#getting-started`} target="_blank" rel="noreferrer">Get started <ArrowUpRight size={14} /></a><a className="button button-outline" href={REPO} target="_blank" rel="noreferrer"><Github size={15} /> Star on GitHub</a></div><span className="start-note">Pre-alpha · Built for the curious.</span></div><div className="install-card"><div className="install-heading"><span><Terminal size={15} /> A little hello from your terminal.</span><button onClick={copyInstall} aria-label="Copy installation commands">{copied ? <Check size={15} /> : <Copy size={15} />}<span>{copied ? "Copied" : "Copy"}</span></button></div><pre><code><span className="code-comment"># Your first conversation starts here</span>{"\n"}<span className="code-command">git clone</span> https://github.com/BenchGrid-dev/slate.git{"\n"}<span className="code-command">cd</span> slate{"\n"}<span className="code-command">cargo build</span> --workspace{"\n"}<span className="code-command">./target/debug/slash</span></code></pre><div className="install-requirements">Linux or macOS · Rust toolchain · Authenticated agent CLI</div><span className="sr-only" role="status">{copied ? "Installation commands copied." : copyError ? "Could not access clipboard. Select and copy the commands above." : ""}</span>{copyError && <p className="copy-error">Select the commands above to copy them manually.</p>}</div></section>

      <section className="faq page-width"><div><h2>Curious? <em>Good.</em></h2></div><div className="faq-list">{[
        ["Is Slate ready for my everyday computer?", "Slate is in pre-alpha. Core workflows run on the development system, while hardware and app compatibility are still expanding. Start with the conversational shell, or try the full desktop on a NixOS test machine or VM. An installable ISO is on the roadmap."],
        ["Can my agent really work while I do?", "In compatible Wayland apps, yes. Slate gives the agent a dedicated input seat with its own pointer, keyboard, and focus. Apps that need your input seat use an explicit fallback: the panel shows ‘controlling’, and Esc gives control back to you. See the project documentation for app compatibility."],
        ["What can I undo?", "Undo restores local files within a recorded task’s scope when a successful btrfs snapshot is available. It does not reverse remote actions, messages, or arbitrary app state. Always use /undo --preview to inspect the recovery plan first. Automatic snapshots and per-tool approvals currently depend on the Claude Code integration; Codex uses its configured sandbox and task-level records."],
        ["Do I need a new AI subscription?", "Slate connects to the official Claude Code or Codex CLI. You use your own supported account and authenticate with that backend. Slate itself does not call model APIs directly. Provider access and usage limits still apply."],
      ].map(([q, a]) => <details key={q}><summary>{q}<Plus size={16} /></summary><p>{a}</p></details>)}</div></section>
    </main>
    <footer className="page-width"><div className="footer-top"><div><Brand footer /><p>A little less human. A lot more possible.</p></div><div className="footer-links"><a href={`${REPO}#documentation`} target="_blank" rel="noreferrer">Documentation <ArrowUpRight size={11} /></a><a href={REPO} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={11} /></a><a href={`${REPO}/blob/main/docs/roadmap.md`} target="_blank" rel="noreferrer">Roadmap <ArrowUpRight size={11} /></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} BenchGrid. All rights reserved.</span><a href={`${REPO}/blob/main/LICENSE`} target="_blank" rel="noreferrer">Slate is licensed under GNU GPL v3.0.</a></div></footer>
  </>;
}
